language: ruby
rvm:
- 2.0.0
notifications:
  email: false
env:
  global:
  - secure: UPTXrTnEtwOW3MZLjGmKmllUflKEQ9ICjELS5j3ucScIyW+q8idf7EEuj03n2FKN/zGNo1BDxLbMxzh+1jBhugGxIF0gmSXQ4tborLMkYtQ07rAWemHGCx3RicDlAWSuqz9tDkMILsasK74LgbfaEeJYI6xfAvOm+em/7jxUk5w=
  - secure: Gkg2vV9NFxvA6TUpl4d10HZNtYB2j1qP5nwlIWuDwV79Wbst2u+sgUX6nCTcQA1L4EgHQqfXXM6NHUrLevT45kj6DuG2C/sJUudttqfB5VmfK7nNT617BlqgiZuNjNWCnD9CK5zAdHUo2ukxiXKyl/WhYIhBA59fsGbFynbUISM=
  - secure: RLWA00fvwiyk2JooX+ePrwPfUCWE1aunuA9STogRiwwUYO237lU35hDkuE7+0GMJAtfWDkuG5f4+8oWsOf0sBytebgxhJ25Uxi6uWlsukuXRM028Z8yjMzgLzmke5InICIVKzPWyvjlphB14nP4PoSrPl9RlHgs4LuJ4l/OkbEQ=
  - secure: RuYxzoTiam6GLIoP3xkhU9eaW3kjyxnOLYqBjjezhEHXrExDQinO5/k2NsHy2Y8iZSlKxMAG+DJJ45WAObNpg3fAPC/ExrzGyNX1u3qCQU481HbVZTJa8vg9IrJsSxCYyawdcbd7tgULiuRZacMmamsXLSJymLofF7LE0jA2KPA=